/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * PokiMani.Api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Envelope,
  EnvelopeDto
} from '../PokiManiApi.schemas';

import { orvalClient } from '.././axiosClient';




export const getApiEnvelopes = (
    
 signal?: AbortSignal
) => {
      
      
      return orvalClient<Envelope[]>(
      {url: `https://localhost:7017/api/envelopes`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiEnvelopesQueryKey = () => {
    return [
    `https://localhost:7017/api/envelopes`
    ] as const;
    }

    
export const getGetApiEnvelopesQueryOptions = <TData = Awaited<ReturnType<typeof getApiEnvelopes>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEnvelopesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEnvelopes>>> = ({ signal }) => getApiEnvelopes(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEnvelopesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEnvelopes>>>
export type GetApiEnvelopesQueryError = void


export function useGetApiEnvelopes<TData = Awaited<ReturnType<typeof getApiEnvelopes>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnvelopes>>,
          TError,
          Awaited<ReturnType<typeof getApiEnvelopes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnvelopes<TData = Awaited<ReturnType<typeof getApiEnvelopes>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnvelopes>>,
          TError,
          Awaited<ReturnType<typeof getApiEnvelopes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnvelopes<TData = Awaited<ReturnType<typeof getApiEnvelopes>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEnvelopes<TData = Awaited<ReturnType<typeof getApiEnvelopes>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEnvelopesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiEnvelopes = (
    envelopeDto: EnvelopeDto,
 signal?: AbortSignal
) => {
      
      
      return orvalClient<Envelope>(
      {url: `https://localhost:7017/api/envelopes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: envelopeDto, signal
    },
      );
    }
  


export const getPostApiEnvelopesMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEnvelopes>>, TError,{data: EnvelopeDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiEnvelopes>>, TError,{data: EnvelopeDto}, TContext> => {

const mutationKey = ['postApiEnvelopes'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiEnvelopes>>, {data: EnvelopeDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiEnvelopes(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiEnvelopesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEnvelopes>>>
    export type PostApiEnvelopesMutationBody = EnvelopeDto
    export type PostApiEnvelopesMutationError = void

    export const usePostApiEnvelopes = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEnvelopes>>, TError,{data: EnvelopeDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiEnvelopes>>,
        TError,
        {data: EnvelopeDto},
        TContext
      > => {

      const mutationOptions = getPostApiEnvelopesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiEnvelopesId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return orvalClient<Envelope>(
      {url: `https://localhost:7017/api/envelopes/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiEnvelopesIdQueryKey = (id?: string,) => {
    return [
    `https://localhost:7017/api/envelopes/${id}`
    ] as const;
    }

    
export const getGetApiEnvelopesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiEnvelopesId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopesId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEnvelopesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEnvelopesId>>> = ({ signal }) => getApiEnvelopesId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEnvelopesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEnvelopesId>>>
export type GetApiEnvelopesIdQueryError = void


export function useGetApiEnvelopesId<TData = Awaited<ReturnType<typeof getApiEnvelopesId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnvelopesId>>,
          TError,
          Awaited<ReturnType<typeof getApiEnvelopesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnvelopesId<TData = Awaited<ReturnType<typeof getApiEnvelopesId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnvelopesId>>,
          TError,
          Awaited<ReturnType<typeof getApiEnvelopesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnvelopesId<TData = Awaited<ReturnType<typeof getApiEnvelopesId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopesId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEnvelopesId<TData = Awaited<ReturnType<typeof getApiEnvelopesId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopesId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEnvelopesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchApiEnvelopesId = (
    id: string,
    envelopeDto: EnvelopeDto,
 ) => {
      
      
      return orvalClient<void>(
      {url: `https://localhost:7017/api/envelopes/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: envelopeDto
    },
      );
    }
  


export const getPatchApiEnvelopesIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiEnvelopesId>>, TError,{id: string;data: EnvelopeDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiEnvelopesId>>, TError,{id: string;data: EnvelopeDto}, TContext> => {

const mutationKey = ['patchApiEnvelopesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiEnvelopesId>>, {id: string;data: EnvelopeDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiEnvelopesId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiEnvelopesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiEnvelopesId>>>
    export type PatchApiEnvelopesIdMutationBody = EnvelopeDto
    export type PatchApiEnvelopesIdMutationError = void

    export const usePatchApiEnvelopesId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiEnvelopesId>>, TError,{id: string;data: EnvelopeDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiEnvelopesId>>,
        TError,
        {id: string;data: EnvelopeDto},
        TContext
      > => {

      const mutationOptions = getPatchApiEnvelopesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiEnvelopesId = (
    id: string,
 ) => {
      
      
      return orvalClient<void>(
      {url: `https://localhost:7017/api/envelopes/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiEnvelopesIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnvelopesId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnvelopesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiEnvelopesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiEnvelopesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiEnvelopesId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiEnvelopesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiEnvelopesId>>>
    
    export type DeleteApiEnvelopesIdMutationError = void

    export const useDeleteApiEnvelopesId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnvelopesId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiEnvelopesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiEnvelopesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    