/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * PokiMani.Api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Account,
  AccountDto
} from '../PokiManiApi.schemas';

import { orvalClient } from '.././axiosClient';




export const getApiAccounts = (
    
 signal?: AbortSignal
) => {
      
      
      return orvalClient<Account[]>(
      {url: `https://localhost:7017/api/accounts`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAccountsQueryKey = () => {
    return [
    `https://localhost:7017/api/accounts`
    ] as const;
    }

    
export const getGetApiAccountsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccounts>>> = ({ signal }) => getApiAccounts(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccounts>>>
export type GetApiAccountsQueryError = void


export function useGetApiAccounts<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccounts>>,
          TError,
          Awaited<ReturnType<typeof getApiAccounts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccounts<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccounts>>,
          TError,
          Awaited<ReturnType<typeof getApiAccounts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccounts<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccounts<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiAccounts = (
    accountDto: AccountDto,
 signal?: AbortSignal
) => {
      
      
      return orvalClient<Account>(
      {url: `https://localhost:7017/api/accounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: accountDto, signal
    },
      );
    }
  


export const getPostApiAccountsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccounts>>, TError,{data: AccountDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccounts>>, TError,{data: AccountDto}, TContext> => {

const mutationKey = ['postApiAccounts'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccounts>>, {data: AccountDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiAccounts(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccounts>>>
    export type PostApiAccountsMutationBody = AccountDto
    export type PostApiAccountsMutationError = void

    export const usePostApiAccounts = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccounts>>, TError,{data: AccountDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccounts>>,
        TError,
        {data: AccountDto},
        TContext
      > => {

      const mutationOptions = getPostApiAccountsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAccountsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return orvalClient<Account>(
      {url: `https://localhost:7017/api/accounts/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAccountsIdQueryKey = (id?: string,) => {
    return [
    `https://localhost:7017/api/accounts/${id}`
    ] as const;
    }

    
export const getGetApiAccountsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountsId>>> = ({ signal }) => getApiAccountsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountsId>>>
export type GetApiAccountsIdQueryError = void


export function useGetApiAccountsId<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountsId<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountsId<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountsId<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchApiAccountsId = (
    id: string,
    accountDto: AccountDto,
 ) => {
      
      
      return orvalClient<Account>(
      {url: `https://localhost:7017/api/accounts/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: accountDto
    },
      );
    }
  


export const getPatchApiAccountsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsId>>, TError,{id: string;data: AccountDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsId>>, TError,{id: string;data: AccountDto}, TContext> => {

const mutationKey = ['patchApiAccountsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAccountsId>>, {id: string;data: AccountDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiAccountsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAccountsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAccountsId>>>
    export type PatchApiAccountsIdMutationBody = AccountDto
    export type PatchApiAccountsIdMutationError = void

    export const usePatchApiAccountsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsId>>, TError,{id: string;data: AccountDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAccountsId>>,
        TError,
        {id: string;data: AccountDto},
        TContext
      > => {

      const mutationOptions = getPatchApiAccountsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiAccountsId = (
    id: string,
 ) => {
      
      
      return orvalClient<void>(
      {url: `https://localhost:7017/api/accounts/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiAccountsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiAccountsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAccountsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiAccountsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAccountsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAccountsId>>>
    
    export type DeleteApiAccountsIdMutationError = void

    export const useDeleteApiAccountsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAccountsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiAccountsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    