/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * PokiMani.Api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateEnvelopeTransactionDto,
  EnvelopeTransaction,
  EnvelopeTransactionDto
} from '../PokiManiApi.schemas';

import { orvalClient } from '.././axiosClient';




export const getApiEnvelopeTransactions = (
    
 signal?: AbortSignal
) => {
      
      
      return orvalClient<EnvelopeTransaction[]>(
      {url: `https://localhost:7017/api/envelope-transactions`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiEnvelopeTransactionsQueryKey = () => {
    return [
    `https://localhost:7017/api/envelope-transactions`
    ] as const;
    }

    
export const getGetApiEnvelopeTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEnvelopeTransactionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEnvelopeTransactions>>> = ({ signal }) => getApiEnvelopeTransactions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEnvelopeTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEnvelopeTransactions>>>
export type GetApiEnvelopeTransactionsQueryError = void


export function useGetApiEnvelopeTransactions<TData = Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnvelopeTransactions>>,
          TError,
          Awaited<ReturnType<typeof getApiEnvelopeTransactions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnvelopeTransactions<TData = Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnvelopeTransactions>>,
          TError,
          Awaited<ReturnType<typeof getApiEnvelopeTransactions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnvelopeTransactions<TData = Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEnvelopeTransactions<TData = Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEnvelopeTransactionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiEnvelopeTransactions = (
    createEnvelopeTransactionDto: CreateEnvelopeTransactionDto,
 signal?: AbortSignal
) => {
      
      
      return orvalClient<EnvelopeTransaction>(
      {url: `https://localhost:7017/api/envelope-transactions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEnvelopeTransactionDto, signal
    },
      );
    }
  


export const getPostApiEnvelopeTransactionsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEnvelopeTransactions>>, TError,{data: CreateEnvelopeTransactionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiEnvelopeTransactions>>, TError,{data: CreateEnvelopeTransactionDto}, TContext> => {

const mutationKey = ['postApiEnvelopeTransactions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiEnvelopeTransactions>>, {data: CreateEnvelopeTransactionDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiEnvelopeTransactions(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiEnvelopeTransactionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEnvelopeTransactions>>>
    export type PostApiEnvelopeTransactionsMutationBody = CreateEnvelopeTransactionDto
    export type PostApiEnvelopeTransactionsMutationError = void

    export const usePostApiEnvelopeTransactions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEnvelopeTransactions>>, TError,{data: CreateEnvelopeTransactionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiEnvelopeTransactions>>,
        TError,
        {data: CreateEnvelopeTransactionDto},
        TContext
      > => {

      const mutationOptions = getPostApiEnvelopeTransactionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiEnvelopeTransactionsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return orvalClient<EnvelopeTransaction>(
      {url: `https://localhost:7017/api/envelope-transactions/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiEnvelopeTransactionsIdQueryKey = (id?: string,) => {
    return [
    `https://localhost:7017/api/envelope-transactions/${id}`
    ] as const;
    }

    
export const getGetApiEnvelopeTransactionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEnvelopeTransactionsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>> = ({ signal }) => getApiEnvelopeTransactionsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEnvelopeTransactionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>>
export type GetApiEnvelopeTransactionsIdQueryError = void


export function useGetApiEnvelopeTransactionsId<TData = Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnvelopeTransactionsId<TData = Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEnvelopeTransactionsId<TData = Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEnvelopeTransactionsId<TData = Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEnvelopeTransactionsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEnvelopeTransactionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchApiEnvelopeTransactionsId = (
    id: string,
    envelopeTransactionDto: EnvelopeTransactionDto,
 ) => {
      
      
      return orvalClient<EnvelopeTransaction>(
      {url: `https://localhost:7017/api/envelope-transactions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: envelopeTransactionDto
    },
      );
    }
  


export const getPatchApiEnvelopeTransactionsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiEnvelopeTransactionsId>>, TError,{id: string;data: EnvelopeTransactionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiEnvelopeTransactionsId>>, TError,{id: string;data: EnvelopeTransactionDto}, TContext> => {

const mutationKey = ['patchApiEnvelopeTransactionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiEnvelopeTransactionsId>>, {id: string;data: EnvelopeTransactionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiEnvelopeTransactionsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiEnvelopeTransactionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiEnvelopeTransactionsId>>>
    export type PatchApiEnvelopeTransactionsIdMutationBody = EnvelopeTransactionDto
    export type PatchApiEnvelopeTransactionsIdMutationError = void

    export const usePatchApiEnvelopeTransactionsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiEnvelopeTransactionsId>>, TError,{id: string;data: EnvelopeTransactionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiEnvelopeTransactionsId>>,
        TError,
        {id: string;data: EnvelopeTransactionDto},
        TContext
      > => {

      const mutationOptions = getPatchApiEnvelopeTransactionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiEnvelopeTransactionsId = (
    id: string,
 ) => {
      
      
      return orvalClient<void>(
      {url: `https://localhost:7017/api/envelope-transactions/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiEnvelopeTransactionsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnvelopeTransactionsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnvelopeTransactionsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiEnvelopeTransactionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiEnvelopeTransactionsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiEnvelopeTransactionsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiEnvelopeTransactionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiEnvelopeTransactionsId>>>
    
    export type DeleteApiEnvelopeTransactionsIdMutationError = void

    export const useDeleteApiEnvelopeTransactionsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEnvelopeTransactionsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiEnvelopeTransactionsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiEnvelopeTransactionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    