/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * PokiMani.Api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccountTransaction,
  AccountTransactionDto,
  CreateAccountTransactionDto
} from '../PokiManiApi.schemas';

import { orvalClient } from '.././axiosClient';




export const getApiAccountTransactions = (
    
 signal?: AbortSignal
) => {
      
      
      return orvalClient<AccountTransaction[]>(
      {url: `https://localhost:7017/api/account-transactions`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAccountTransactionsQueryKey = () => {
    return [
    `https://localhost:7017/api/account-transactions`
    ] as const;
    }

    
export const getGetApiAccountTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountTransactions>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountTransactionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountTransactions>>> = ({ signal }) => getApiAccountTransactions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountTransactions>>>
export type GetApiAccountTransactionsQueryError = void


export function useGetApiAccountTransactions<TData = Awaited<ReturnType<typeof getApiAccountTransactions>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountTransactions>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountTransactions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTransactions<TData = Awaited<ReturnType<typeof getApiAccountTransactions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountTransactions>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountTransactions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTransactions<TData = Awaited<ReturnType<typeof getApiAccountTransactions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountTransactions<TData = Awaited<ReturnType<typeof getApiAccountTransactions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountTransactionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiAccountTransactions = (
    createAccountTransactionDto: CreateAccountTransactionDto,
 signal?: AbortSignal
) => {
      
      
      return orvalClient<AccountTransaction>(
      {url: `https://localhost:7017/api/account-transactions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccountTransactionDto, signal
    },
      );
    }
  


export const getPostApiAccountTransactionsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountTransactions>>, TError,{data: CreateAccountTransactionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountTransactions>>, TError,{data: CreateAccountTransactionDto}, TContext> => {

const mutationKey = ['postApiAccountTransactions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountTransactions>>, {data: CreateAccountTransactionDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountTransactions(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountTransactionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountTransactions>>>
    export type PostApiAccountTransactionsMutationBody = CreateAccountTransactionDto
    export type PostApiAccountTransactionsMutationError = void

    export const usePostApiAccountTransactions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountTransactions>>, TError,{data: CreateAccountTransactionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountTransactions>>,
        TError,
        {data: CreateAccountTransactionDto},
        TContext
      > => {

      const mutationOptions = getPostApiAccountTransactionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAccountTransactionsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return orvalClient<AccountTransaction>(
      {url: `https://localhost:7017/api/account-transactions/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAccountTransactionsIdQueryKey = (id?: string,) => {
    return [
    `https://localhost:7017/api/account-transactions/${id}`
    ] as const;
    }

    
export const getGetApiAccountTransactionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountTransactionsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountTransactionsId>>> = ({ signal }) => getApiAccountTransactionsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountTransactionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountTransactionsId>>>
export type GetApiAccountTransactionsIdQueryError = void


export function useGetApiAccountTransactionsId<TData = Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountTransactionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountTransactionsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTransactionsId<TData = Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountTransactionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountTransactionsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTransactionsId<TData = Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountTransactionsId<TData = Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTransactionsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountTransactionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchApiAccountTransactionsId = (
    id: string,
    accountTransactionDto: AccountTransactionDto,
 ) => {
      
      
      return orvalClient<AccountTransaction>(
      {url: `https://localhost:7017/api/account-transactions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: accountTransactionDto
    },
      );
    }
  


export const getPatchApiAccountTransactionsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountTransactionsId>>, TError,{id: string;data: AccountTransactionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountTransactionsId>>, TError,{id: string;data: AccountTransactionDto}, TContext> => {

const mutationKey = ['patchApiAccountTransactionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAccountTransactionsId>>, {id: string;data: AccountTransactionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiAccountTransactionsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAccountTransactionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAccountTransactionsId>>>
    export type PatchApiAccountTransactionsIdMutationBody = AccountTransactionDto
    export type PatchApiAccountTransactionsIdMutationError = void

    export const usePatchApiAccountTransactionsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountTransactionsId>>, TError,{id: string;data: AccountTransactionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAccountTransactionsId>>,
        TError,
        {id: string;data: AccountTransactionDto},
        TContext
      > => {

      const mutationOptions = getPatchApiAccountTransactionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiAccountTransactionsId = (
    id: string,
 ) => {
      
      
      return orvalClient<void>(
      {url: `https://localhost:7017/api/account-transactions/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiAccountTransactionsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountTransactionsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountTransactionsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiAccountTransactionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAccountTransactionsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiAccountTransactionsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAccountTransactionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAccountTransactionsId>>>
    
    export type DeleteApiAccountTransactionsIdMutationError = void

    export const useDeleteApiAccountTransactionsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountTransactionsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAccountTransactionsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiAccountTransactionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    