/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * PokiMani.Api
 * OpenAPI spec version: 1.0
 */
export interface Account {
  id?: string;
  userId: string;
  /** @nullable */
  name: string | null;
  createdDate: string;
  /** @nullable */
  closedDate?: string | null;
  balance?: number;
}

export interface AccountDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  createdDate?: string | null;
  /** @nullable */
  closedDate?: string | null;
  /** @nullable */
  balance?: number | null;
}

export interface AccountTransaction {
  id?: string;
  userId: string;
  accountId: string;
  account?: Account;
  amount: number;
  /** @nullable */
  memo?: string | null;
  /** @nullable */
  notes?: string | null;
  cleared: boolean;
  reconciled: boolean;
  /** @nullable */
  payee?: string | null;
}

export interface AccountTransactionDto {
  id?: string;
  /** @nullable */
  accountId?: string | null;
  account?: Account;
  /** @nullable */
  amount?: number | null;
  /** @nullable */
  memo?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  cleared?: boolean | null;
  /** @nullable */
  reconciled?: boolean | null;
  /** @nullable */
  payee?: string | null;
}

export interface AddUserDto {
  /** @nullable */
  name: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  password: string | null;
  /** @nullable */
  phone?: string | null;
}

export interface CreateAccountTransactionDto {
  accountId: string;
  amount: number;
  /** @nullable */
  memo?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  payee?: string | null;
}

export interface CreateEnvelopeTransactionDto {
  /** @nullable */
  envelopeId?: string | null;
  /** @nullable */
  accountTransactionId?: string | null;
  amount?: number;
}

export interface Envelope {
  id?: string;
  userId: string;
  /** @nullable */
  parentId?: string | null;
  parent?: Envelope;
  /** @nullable */
  name?: string | null;
  isParent: boolean;
  /** @nullable */
  dateDestroyed?: string | null;
  dateCreated: string;
  balance: number;
  /** @nullable */
  color?: string | null;
}

export interface EnvelopeDto {
  /** @nullable */
  balance?: number | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  isParent?: boolean | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  parentId?: string | null;
  /** @nullable */
  dateCreated?: string | null;
  /** @nullable */
  dateDestroyed?: string | null;
}

export interface EnvelopeTransaction {
  id?: string;
  userId: string;
  /** @nullable */
  envelopeId?: string | null;
  envelope?: Envelope;
  /** @nullable */
  accountTransactionId?: string | null;
  accountTransaction?: AccountTransaction;
  amount: number;
}

export interface EnvelopeTransactionDto {
  /** @nullable */
  envelopeId?: string | null;
  /** @nullable */
  accountTransactionId?: string | null;
  /** @nullable */
  amount?: number | null;
}

export interface SessionDto {
  /** @nullable */
  userName: string | null;
  /** @nullable */
  password: string | null;
}

export interface TokenDto {
  /** @nullable */
  accessToken: string | null;
}

